
server:
  port: 8081

# \u6700\u4F73\u5B9E\u8DF5\uFF1Aspringcloud\u5E94\u7528\u90FD\u8981\u6307\u5B9Aapplication.name
spring:
  application:
    name: springcloud-eureka-server

#  \u5728\u9ED8\u8BA4\u60C5\u51B5\u4E0Berureka server\u4E5F\u662F\u4E00\u4E2Aeureka client ,\u5FC5\u987B\u8981\u6307\u5B9A\u4E00\u4E2A server
eureka:
  instance:
    hostname: localhost
  client:
    #   registerWithEureka\u548CfetchRegistry=false \u8868\u660E\u81EA\u5DF1\u662F\u4E00\u4E2Aeureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/